[package]
name = "vnet"
version = "0.1.0"
authors = ["Mikhail Gordeev <gordmisha@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
caps = "0.5.0"
clap = "2.33.3"
